// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bvbcdxrjaxrqvbsazmjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ2YmNkeHJqYXhycXZic2F6bWprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4NDM4NzIsImV4cCI6MjA3MzQxOTg3Mn0.q2rduF0Q96cKeBiFeDEL2PS4ov0nUe8lBk1-I78bvIA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});